### ISSUE TITLE
institution_id registration of MOHC (Met Office Hadley Centre)

### ISSUE THREAD

**Issue by gredmond-mo** [WCRP-CORDEX/cordex-cmip6-cv#163] opened 2024-09-11 14:13 UTC
### institution_id

MOHC

### institution

Met Office Hadley Centre, Exeter, United Kingdom

**Comment by jesusff** [comment] 2024-09-12 14:29
Duplicate of #49 

@gredmond-mo do you want to update the entry for MOHC? The only difference I see in this new request is the expanded form "United Kingdom" instead of "UK"

**Comment by gredmond-mo** [comment] 2024-09-12 14:41
Hi Jesus, no sorry, this is a duplicate, I must have been looking at an old version of the institution CV in which MOHC wasn't included. This can be closed as a duplicate.

**Comment by jesusff** [comment] 2024-09-12 16:26
no worries :-) I close it, then

**Closed by jesusff** 2024-09-12 16:26 UTC
Labels: Register institution_id
