### ISSUE TITLE
add domain id SEA-12

### ISSUE THREAD

**Issue by gredmond-mo** [WCRP-CORDEX/cordex-cmip6-cv#164] opened 2024-09-11 14:17 UTC
We are running some 12km CORDEX experiments over the SEA domain, could it be added to the domain id CV please?

        "SEA-12": {
            "domain": "South East Asia",
            "domain_id": "SEA-12"
        },

Thanks very much,

Grace

**Comment by jesusff** [comment] 2024-09-12 14:38
Sorry @gredmond-mo , this was moved (https://github.com/WCRP-CORDEX/domain-tables/issues/11) and still pending.

I'll close this issue as duplicate of https://github.com/WCRP-CORDEX/domain-tables/issues/11, as the new domain needs to be added in the domain-tables and the file in this CV is automatically generated from that info (right, @larsbuntemeyer ?)

**Closed** 2024-09-12 14:38 UTC
